import imgItem from "../../../assets/photoItem.png";
import imgItem2 from "../../../assets/photoItem2.png";
import personImg from "../../../assets/photoPerson.png";
import personImg2 from "../../../assets/photoPerson2.png";
import personImg3 from "../../../assets/photoPerson3.png";

export const data = [{
        id: "1",
        img: imgItem,
        personImg: personImg,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "2",
        img: imgItem2,
        personImg: personImg2,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "3",
        img: imgItem,
        personImg: personImg3,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "4",
        img: imgItem2,
        personImg: personImg,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "5",
        img: imgItem,
        personImg: personImg2,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "6",
        img: imgItem2,
        personImg: personImg3,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "7",
        img: imgItem,
        personImg: personImg,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "8",
        img: imgItem2,
        personImg: personImg2,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "9",
        img: imgItem,
        personImg: personImg3,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "10",
        img: imgItem2,
        personImg: personImg,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "11",
        img: imgItem,
        personImg: personImg2,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
    {
        id: "12",
        img: imgItem2,
        personImg: personImg3,
        title: "New Apartment Nice Wiew",
        paragh: "Quincy St, Brooklyn, NY, USA",
        oldPrice: "$2,800/mo",
        price: "$7,500/mo",
    },
];