import bgImg from "../assets/imgbg/bg.svg";

export const home = [{
        id: 1,
        bgImg: bgImg,
        title: "Skyper Pool Partment",
        p: "112 Glenwood Ave Hyde Park, Boston, MA",
        bed: "4 beds",
        bath: "5 Baths",
        garage: "1 Garage",
        sqrt: "1200 Sq Ft",
        price: "$5,250/mo",
    },
    {
        id: 2,
        bgImg: bgImg,
        title: "Skyper Pool",
        p: "112 Glenwood Ave Hyde Park, Boston, MA",
        bed: "8 beds",
        bath: "5 Baths",
        garage: "1 Garage",
        sqrt: "1200 Sq Ft",
        price: "$8,250/mo",
    },
    {
        id: 3,
        bgImg: bgImg,
        title: "Skyper House Partment",
        p: "112 Glenwood Ave Hyde Park, Boston, MA",
        bed: "2 beds",
        bath: "1 Baths",
        garage: "3 Garage",
        sqrt: "1200 Sq Ft",
        price: "$15,250/mo",
    },
];